<?php

namespace Modules\Menu\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class MenuDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        $menus = [
            [
                "id" => 3,
                "is_active" => true,
                "name" => "منوی اصلی",
            ],
            [
                "id" => 4,
                "is_active" => true,
                "name" => "منوی دسته بندی",
            ],
            [
                "id" => 5,
                "is_active" => true,
                "name" => "منوی فوتر 1",
            ],
            [
                "id" => 6,
                "is_active" => true,
                "name" => "منوی فوتر 2",
            ]
        ];

        foreach ($menus as $menu) {
            DB::table('menus')->insert([
                "id" => $menu['id'],
                "is_active" => $menu['is_active'],
                "created_at" => now(),
                "updated_at" => now(),
            ]);

            DB::table('menu_translations')->insert([
                "menu_id" => $menu['id'],
                "locale" => 'fa',
                "name" => $menu['name'],
            ]);
        }


        $menuItems = [
            [
                "id" => 6,
                "menu_id" => 3,
                "parent_id" => null,
                "category_id" => null,
                "page_id" => null,
                "type" => "URL",
                "url" => null,
                "icon" => null,
                "target" => "_self",
                "position" => 0,
                "is_root" => true,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "ریشه",
            ],
            [
                "id" => 8,
                "menu_id" => 4,
                "parent_id" => null,
                "category_id" => null,
                "page_id" => null,
                "type" => "URL",
                "url" => null,
                "icon" => null,
                "target" => "_self",
                "position" => 0,
                "is_root" => true,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "ریشه",
            ],
            [
                "id" => 30,
                "menu_id" => 5,
                "parent_id" => null,
                "category_id" => null,
                "page_id" => null,
                "type" => "URL",
                "url" => null,
                "icon" => null,
                "target" => "_self",
                "position" => 0,
                "is_root" => true,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "ریشه",
            ],
            [
                "id" => 36,
                "menu_id" => 6,
                "parent_id" => null,
                "category_id" => null,
                "page_id" => null,
                "type" => "URL",
                "url" => null,
                "icon" => null,
                "target" => "_self",
                "position" => 0,
                "is_root" => true,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "ریشه",
            ],
            [
                "id" => 7,
                "menu_id" => 3,
                "parent_id" => 6,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/products",
                "icon" => null,
                "target" => "_self",
                "position" => 0,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "فروشگاه",
            ],
            [
                "id" => 9,
                "menu_id" => 4,
                "parent_id" => 8,
                "category_id" => 181,
                "page_id" => null,
                "type" => "category",
                "url" => null,
                "icon" => "las la-car-battery",
                "target" => "_self",
                "position" => 0,
                "is_root" => false,
                "is_fluid" => true,
                "is_active" => true,
                "name" => "الکترونیک",
            ],
            [
                "id" => 10,
                "menu_id" => 4,
                "parent_id" => 8,
                "category_id" => 12,
                "page_id" => null,
                "type" => "category",
                "url" => null,
                "icon" => "las la-tshirt",
                "target" => "_self",
                "position" => 1,
                "is_root" => false,
                "is_fluid" => true,
                "is_active" => true,
                "name" => "مد مردانه",
            ],
            [
                "id" => 11,
                "menu_id" => 4,
                "parent_id" => 8,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/categories/laptops/products",
                "icon" => "las la-laptop",
                "target" => "_self",
                "position" => 2,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "لپ‌تاپ",
            ],
            [
                "id" => 12,
                "menu_id" => 4,
                "parent_id" => 11,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/brands/hp/products",
                "icon" => null,
                "target" => "_self",
                "position" => 0,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "اچ‌پی",
            ],
            [
                "id" => 13,
                "menu_id" => 4,
                "parent_id" => 11,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/categories/huawei/products",
                "icon" => null,
                "target" => "_self",
                "position" => 1,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "هوآوی",
            ],
            [
                "id" => 14,
                "menu_id" => 4,
                "parent_id" => 11,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/brands/asus/products",
                "icon" => null,
                "target" => "_self",
                "position" => 2,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "ایسوس",
            ],
            [
                "id" => 15,
                "menu_id" => 4,
                "parent_id" => 11,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/brands/apple/products",
                "icon" => null,
                "target" => "_self",
                "position" => 3,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "اپل",
            ],
            [
                "id" => 16,
                "menu_id" => 4,
                "parent_id" => 8,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/categories/mobiles/products",
                "icon" => "las la-mobile",
                "target" => "_self",
                "position" => 3,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "موبایل",
            ],
            [
                "id" => 17,
                "menu_id" => 4,
                "parent_id" => 8,
                "category_id" => 181,
                "page_id" => null,
                "type" => "category",
                "url" => null,
                "icon" => "las la-microchip",
                "target" => "_self",
                "position" => 4,
                "is_root" => false,
                "is_fluid" => true,
                "is_active" => true,
                "name" => "الکترونیک مصرفی",
            ],
            [
                "id" => 18,
                "menu_id" => 4,
                "parent_id" => 8,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/categories/televisions/products",
                "icon" => "las la-tv",
                "target" => "_self",
                "position" => 5,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "تلویزیون",
            ],
            [
                "id" => 19,
                "menu_id" => 4,
                "parent_id" => 8,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/categories/watches/products",
                "icon" => "lar la-clock",
                "target" => "_self",
                "position" => 6,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "ساعت",
            ],
            [
                "id" => 20,
                "menu_id" => 4,
                "parent_id" => 8,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/categories/mens-fashion/products",
                "icon" => "las la-tshirt",
                "target" => "_self",
                "position" => 7,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "مد",
            ],
            [
                "id" => 21,
                "menu_id" => 4,
                "parent_id" => 20,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/categories/mens-fashion/products",
                "icon" => null,
                "target" => "_self",
                "position" => 0,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "مد مردانه",
            ],
            [
                "id" => 22,
                "menu_id" => 4,
                "parent_id" => 20,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/categories/womens-fashion/products",
                "icon" => null,
                "target" => "_self",
                "position" => 1,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "مد زنانه",
            ],
            [
                "id" => 23,
                "menu_id" => 4,
                "parent_id" => 8,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/categories/backpacks/products",
                "icon" => "las la-suitcase-rolling",
                "target" => "_self",
                "position" => 8,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "کوله پشتی",
            ],
            [
                "id" => 24,
                "menu_id" => 4,
                "parent_id" => 8,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/categories/tablets/products",
                "icon" => "las la-tablet",
                "target" => "_self",
                "position" => 9,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "تبلت",
            ],
            [
                "id" => 25,
                "menu_id" => 4,
                "parent_id" => 8,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/categories/mobile-headphones/products",
                "icon" => "las la-headphones",
                "target" => "_self",
                "position" => 10,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "هدفون",
            ],
            [
                "id" => 26,
                "menu_id" => 4,
                "parent_id" => 8,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/categories/hot-sale/products",
                "icon" => "las la-fire",
                "target" => "_self",
                "position" => 11,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "فروش ویژه",
            ],
            [
                "id" => 27,
                "menu_id" => 4,
                "parent_id" => 8,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/categories/shoes/products",
                "icon" => "las la-shoe-prints",
                "target" => "_self",
                "position" => 12,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "کفش",
            ],
            [
                "id" => 28,
                "menu_id" => 3,
                "parent_id" => 6,
                "category_id" => null,
                "page_id" => 2,
                "type" => "page",
                "url" => null,
                "icon" => null,
                "target" => "_self",
                "position" => 1,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "پرسش‌های متداول",
            ],
            [
                "id" => 29,
                "menu_id" => 3,
                "parent_id" => 6,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "#",
                "icon" => null,
                "target" => "_blank",
                "position" => 2,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "خرید قالب!",
            ],
            [
                "id" => 31,
                "menu_id" => 5,
                "parent_id" => 30,
                "category_id" => null,
                "page_id" => 1,
                "type" => "page",
                "url" => null,
                "icon" => null,
                "target" => "_self",
                "position" => 0,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "درباره ما",
            ],
            [
                "id" => 32,
                "menu_id" => 5,
                "parent_id" => 30,
                "category_id" => null,
                "page_id" => 3,
                "type" => "page",
                "url" => null,
                "icon" => null,
                "target" => "_self",
                "position" => 1,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "سیاست بازگشت",
            ],
            [
                "id" => 33,
                "menu_id" => 5,
                "parent_id" => 30,
                "category_id" => null,
                "page_id" => 2,
                "type" => "page",
                "url" => null,
                "icon" => null,
                "target" => "_self",
                "position" => 2,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "پرسش‌های متداول",
            ],
            [
                "id" => 34,
                "menu_id" => 5,
                "parent_id" => 30,
                "category_id" => null,
                "page_id" => 5,
                "type" => "page",
                "url" => null,
                "icon" => null,
                "target" => "_self",
                "position" => 3,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "حریم خصوصی و سیاست",
            ],
            [
                "id" => 35,
                "menu_id" => 5,
                "parent_id" => 30,
                "category_id" => null,
                "page_id" => 4,
                "type" => "page",
                "url" => null,
                "icon" => null,
                "target" => "_self",
                "position" => 4,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "شرایط استفاده",
            ],
            [
                "id" => 37,
                "menu_id" => 6,
                "parent_id" => 36,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/brands/msi/products",
                "icon" => null,
                "target" => "_self",
                "position" => null,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "تخفیف‌های ویژه",
            ],
            [
                "id" => 38,
                "menu_id" => 6,
                "parent_id" => 36,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/categories/backpacks/products",
                "icon" => null,
                "target" => "_self",
                "position" => null,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "کوله پشتی",
            ],
            [
                "id" => 39,
                "menu_id" => 6,
                "parent_id" => 36,
                "category_id" => null,
                "page_id" => null,
                "type" => "url",
                "url" => "/categories/mens-fashion/products",
                "icon" => null,
                "target" => "_self",
                "position" => null,
                "is_root" => false,
                "is_fluid" => false,
                "is_active" => true,
                "name" => "مد مردانه",
            ]
        ];

        $menuItems = collect($menuItems);

        foreach ($menuItems->sortBy('id') as $menuItem) {
            DB::table('menu_items')->insert([
                "id" => $menuItem["id"],
                "menu_id" => $menuItem["menu_id"],
                "parent_id" => $menuItem["parent_id"],
                "category_id" => $menuItem["category_id"],
                "page_id" => $menuItem["page_id"],
                "type" => $menuItem["type"],
                "url" => $menuItem["url"],
                "icon" => $menuItem["icon"],
                "target" => $menuItem["target"],
                "position" => $menuItem["position"],
                "is_root" => $menuItem["is_root"],
                "is_fluid" => $menuItem["is_fluid"],
                "is_active" => $menuItem["is_active"],
                "created_at" => now(),
                "updated_at" => now(),
            ]);

            DB::table('menu_item_translations')->insert([
                "menu_item_id" => $menuItem["id"],
                "locale" => 'fa',
                "name" => $menuItem["name"],
            ]);
        }
    }
}
