<?php

namespace Modules\Setting\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Modules\Setting\Entities\Setting;

class SettingDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $settings = [
            0 => [
                'id' => 52,
                'key' => 'storefront_copyright_text',
                'is_translatable' => 1,
                'plain_value' => 's:92:"Copyright © <a href="{{ store_url }}">{{ store_name }}</a> {{ year }}. All rights reserved.";',
                'value' => 's:116:"کپی رایت © <a href="{{ store_url }}">{{ store_name }}</a> {{ year }}. تمامی حقوق محفوظ است.";',
            ],
            1 => [
                'id' => 201,
                'key' => 'storefront_welcome_text',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:38:"به پویالند خوش آمدید";',
            ],
            2 => [
                'id' => 202,
                'key' => 'storefront_address',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 'N;',
            ],
            3 => [
                'id' => 203,
                'key' => 'storefront_navbar_text',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:74:"ارسال رایگان برای سفارشات بالای 1 میلیون!";',
            ],
            4 => [
                'id' => 204,
                'key' => 'storefront_footer_menu_one_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:15:"خدمات ما";',
            ],
            5 => [
                'id' => 205,
                'key' => 'storefront_footer_menu_two_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:14:"اطلاعات";',
            ],
            6 => [
                'id' => 206,
                'key' => 'storefront_feature_1_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:30:"پشتیبانی 24 ساعته";',
            ],
            7 => [
                'id' => 207,
                'key' => 'storefront_feature_1_subtitle',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:23:"پشتیبانی قوی";',
            ],
            8 => [
                'id' => 208,
                'key' => 'storefront_feature_2_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:25:"پرداخت آنلاین";',
            ],
            9 => [
                'id' => 209,
                'key' => 'storefront_feature_2_subtitle',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:55:"پرداخت با تمامی کارت های بانکی";',
            ],
            10 => [
                'id' => 210,
                'key' => 'storefront_feature_3_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:17:"پراخت امن";',
            ],
            11 => [
                'id' => 211,
                'key' => 'storefront_feature_3_subtitle',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:13:"100% ایمن";',
            ],
            12 => [
                'id' => 212,
                'key' => 'storefront_feature_4_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:23:"ارسال رایگان";',
            ],
            13 => [
                'id' => 213,
                'key' => 'storefront_feature_4_subtitle',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:49:"برای سفارشات بالای 1 میلیون";',
            ],
            14 => [
                'id' => 214,
                'key' => 'storefront_feature_5_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:30:"ضمانت بازگشت پول";',
            ],
            15 => [
                'id' => 215,
                'key' => 'storefront_feature_5_subtitle',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:26:"گارانتی 30 روزه";',
            ],
            16 => [
                'id' => 216,
                'key' => 'storefront_product_page_banner_file_id',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:4:"1389";',
            ],
            17 => [
                'id' => 217,
                'key' => 'storefront_slider_banner_1_file_id',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:4:"1383";',
            ],
            18 => [
                'id' => 218,
                'key' => 'storefront_slider_banner_2_file_id',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:4:"1384";',
            ],
            19 => [
                'id' => 219,
                'key' => 'storefront_three_column_full_width_banners_1_file_id',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:4:"1361";',
            ],
            20 => [
                'id' => 220,
                'key' => 'storefront_three_column_full_width_banners_2_file_id',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:4:"1368";',
            ],
            21 => [
                'id' => 221,
                'key' => 'storefront_three_column_full_width_banners_3_file_id',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:4:"1363";',
            ],
            22 => [
                'id' => 222,
                'key' => 'storefront_featured_categories_section_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:33:"دسته بندی های برتر";',
            ],
            23 => [
                'id' => 223,
                'key' => 'storefront_featured_categories_section_subtitle',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:229:"ماه گذشته بیش از ۱۵۰۰ محصول از این دسته بندی ها به فروش رسید. می‌توانید یک محصول از اینجا انتخاب کنید و با قیمت بهتری تهیه کنید.";',
            ],
            24 => [
                'id' => 224,
                'key' => 'storefront_product_tabs_1_section_tab_1_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:8:"ویژه";',
            ],
            25 => [
                'id' => 225,
                'key' => 'storefront_product_tabs_1_section_tab_2_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:6:"خاص";',
            ],
            26 => [
                'id' => 226,
                'key' => 'storefront_product_tabs_1_section_tab_3_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:8:"جدید";',
            ],
            27 => [
                'id' => 227,
                'key' => 'storefront_product_tabs_1_section_tab_4_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:10:"آخرین";',
            ],
            28 => [
                'id' => 228,
                'key' => 'storefront_two_column_banners_1_file_id',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:4:"1364";',
            ],
            29 => [
                'id' => 229,
                'key' => 'storefront_two_column_banners_2_file_id',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:4:"1367";',
            ],
            30 => [
                'id' => 230,
                'key' => 'storefront_product_grid_section_tab_1_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:12:"موبایل";',
            ],
            31 => [
                'id' => 231,
                'key' => 'storefront_product_grid_section_tab_2_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:17:"مد مردانه";',
            ],
            32 => [
                'id' => 232,
                'key' => 'storefront_product_grid_section_tab_3_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:10:"لپتاپ";',
            ],
            33 => [
                'id' => 233,
                'key' => 'storefront_product_grid_section_tab_4_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:8:"تبلت";',
            ],
            34 => [
                'id' => 234,
                'key' => 'storefront_three_column_banners_1_file_id',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:4:"1369";',
            ],
            35 => [
                'id' => 235,
                'key' => 'storefront_three_column_banners_2_file_id',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:4:"1371";',
            ],
            36 => [
                'id' => 236,
                'key' => 'storefront_three_column_banners_3_file_id',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:4:"1372";',
            ],
            37 => [
                'id' => 237,
                'key' => 'storefront_product_tabs_2_section_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:26:"پرفروش ترین ها";',
            ],
            38 => [
                'id' => 238,
                'key' => 'storefront_product_tabs_2_section_tab_1_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:25:"آخرین محصولات";',
            ],
            39 => [
                'id' => 239,
                'key' => 'storefront_product_tabs_2_section_tab_2_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:27:"آخرین بازدیدها";',
            ],
            40 => [
                'id' => 240,
                'key' => 'storefront_product_tabs_2_section_tab_3_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:8:"حراج";',
            ],
            41 => [
                'id' => 241,
                'key' => 'storefront_product_tabs_2_section_tab_4_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:21:"پرفروش ترین";',
            ],
            42 => [
                'id' => 242,
                'key' => 'storefront_one_column_banner_file_id',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:4:"1373";',
            ],
            43 => [
                'id' => 243,
                'key' => 'storefront_theme_color',
                'is_translatable' => 0,
                'plain_value' => 's:4:"blue";',
            ],
            44 => [
                'id' => 244,
                'key' => 'storefront_custom_theme_color',
                'is_translatable' => 0,
                'plain_value' => 's:7:"#000000";',
            ],
            45 => [
                'id' => 245,
                'key' => 'storefront_mail_theme_color',
                'is_translatable' => 0,
                'plain_value' => 's:4:"blue";',
            ],
            46 => [
                'id' => 246,
                'key' => 'storefront_custom_mail_theme_color',
                'is_translatable' => 0,
                'plain_value' => 's:7:"#000000";',
            ],
            47 => [
                'id' => 247,
                'key' => 'storefront_slider',
                'is_translatable' => 0,
                'plain_value' => 's:1:"1";',
            ],
            48 => [
                'id' => 248,
                'key' => 'storefront_terms_page',
                'is_translatable' => 0,
                'plain_value' => 's:1:"3";',
            ],
            49 => [
                'id' => 249,
                'key' => 'storefront_privacy_page',
                'is_translatable' => 0,
                'plain_value' => 's:1:"5";',
            ],
            50 => [
                'id' => 250,
                'key' => 'storefront_most_searched_keywords_enabled',
                'is_translatable' => 0,
                'plain_value' => 's:1:"0";',
            ],
            51 => [
                'id' => 251,
                'key' => 'storefront_primary_menu',
                'is_translatable' => 0,
                'plain_value' => 's:1:"3";',
            ],
            52 => [
                'id' => 252,
                'key' => 'storefront_category_menu',
                'is_translatable' => 0,
                'plain_value' => 's:1:"4";',
            ],
            53 => [
                'id' => 253,
                'key' => 'storefront_footer_menu_one',
                'is_translatable' => 0,
                'plain_value' => 's:1:"5";',
            ],
            54 => [
                'id' => 254,
                'key' => 'storefront_footer_menu_two',
                'is_translatable' => 0,
                'plain_value' => 's:1:"6";',
            ],
            55 => [
                'id' => 255,
                'key' => 'storefront_features_section_enabled',
                'is_translatable' => 0,
                'plain_value' => 's:1:"1";',
            ],
            56 => [
                'id' => 256,
                'key' => 'storefront_feature_1_icon',
                'is_translatable' => 0,
                'plain_value' => 's:17:"las la-headphones";',
            ],
            57 => [
                'id' => 257,
                'key' => 'storefront_feature_2_icon',
                'is_translatable' => 0,
                'plain_value' => 's:18:"las la-credit-card";',
            ],
            58 => [
                'id' => 258,
                'key' => 'storefront_feature_3_icon',
                'is_translatable' => 0,
                'plain_value' => 's:17:"las la-shield-alt";',
            ],
            59 => [
                'id' => 259,
                'key' => 'storefront_feature_4_icon',
                'is_translatable' => 0,
                'plain_value' => 's:12:"las la-truck";',
            ],
            60 => [
                'id' => 260,
                'key' => 'storefront_feature_5_icon',
                'is_translatable' => 0,
                'plain_value' => 's:21:"las la-calendar-minus";',
            ],
            61 => [
                'id' => 261,
                'key' => 'storefront_product_page_banner_call_to_action_url',
                'is_translatable' => 0,
                'plain_value' => 's:31:"/categories/headphones/products";',
            ],
            62 => [
                'id' => 262,
                'key' => 'storefront_product_page_banner_open_in_new_window',
                'is_translatable' => 0,
                'plain_value' => 's:1:"0";',
            ],
            63 => [
                'id' => 263,
                'key' => 'storefront_facebook_link',
                'is_translatable' => 0,
                'plain_value' => 's:1:"#";',
            ],
            64 => [
                'id' => 264,
                'key' => 'storefront_twitter_link',
                'is_translatable' => 0,
                'plain_value' => 's:1:"#";',
            ],
            65 => [
                'id' => 265,
                'key' => 'storefront_instagram_link',
                'is_translatable' => 0,
                'plain_value' => 's:1:"#";',
            ],
            66 => [
                'id' => 266,
                'key' => 'storefront_youtube_link',
                'is_translatable' => 0,
                'plain_value' => 's:1:"#";',
            ],
            67 => [
                'id' => 267,
                'key' => 'storefront_slider_banner_1_call_to_action_url',
                'is_translatable' => 0,
                'plain_value' => 's:30:"/categories/backpacks/products";',
            ],
            68 => [
                'id' => 268,
                'key' => 'storefront_slider_banner_1_open_in_new_window',
                'is_translatable' => 0,
                'plain_value' => 's:1:"0";',
            ],
            69 => [
                'id' => 269,
                'key' => 'storefront_slider_banner_2_call_to_action_url',
                'is_translatable' => 0,
                'plain_value' => 's:27:"/categories/iphone/products";',
            ],
            70 => [
                'id' => 270,
                'key' => 'storefront_slider_banner_2_open_in_new_window',
                'is_translatable' => 0,
                'plain_value' => 's:1:"1";',
            ],
            71 => [
                'id' => 271,
                'key' => 'storefront_three_column_full_width_banners_enabled',
                'is_translatable' => 0,
                'plain_value' => 's:1:"1";',
            ],
            72 => [
                'id' => 272,
                'key' => 'storefront_three_column_full_width_banners_1_call_to_action_url',
                'is_translatable' => 0,
                'plain_value' => 's:36:"/categories/home-appliances/products";',
            ],
            73 => [
                'id' => 273,
                'key' => 'storefront_three_column_full_width_banners_1_open_in_new_window',
                'is_translatable' => 0,
                'plain_value' => 's:1:"0";',
            ],
            74 => [
                'id' => 274,
                'key' => 'storefront_three_column_full_width_banners_2_call_to_action_url',
                'is_translatable' => 0,
                'plain_value' => 's:36:"/categories/home-appliances/products";',
            ],
            75 => [
                'id' => 275,
                'key' => 'storefront_three_column_full_width_banners_2_open_in_new_window',
                'is_translatable' => 0,
                'plain_value' => 's:1:"0";',
            ],
            76 => [
                'id' => 276,
                'key' => 'storefront_three_column_full_width_banners_3_call_to_action_url',
                'is_translatable' => 0,
                'plain_value' => 's:28:"/categories/samsung/products";',
            ],
            77 => [
                'id' => 277,
                'key' => 'storefront_three_column_full_width_banners_3_open_in_new_window',
                'is_translatable' => 0,
                'plain_value' => 's:1:"0";',
            ],
            78 => [
                'id' => 278,
                'key' => 'storefront_featured_categories_section_enabled',
                'is_translatable' => 0,
                'plain_value' => 's:1:"1";',
            ],
            79 => [
                'id' => 279,
                'key' => 'storefront_featured_categories_section_category_1_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:3:"182";',
            ],
            80 => [
                'id' => 280,
                'key' => 'storefront_featured_categories_section_category_1_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            81 => [
                'id' => 281,
                'key' => 'storefront_featured_categories_section_category_1_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            82 => [
                'id' => 282,
                'key' => 'storefront_featured_categories_section_category_2_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:3:"183";',
            ],
            83 => [
                'id' => 283,
                'key' => 'storefront_featured_categories_section_category_2_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            84 => [
                'id' => 284,
                'key' => 'storefront_featured_categories_section_category_2_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            85 => [
                'id' => 285,
                'key' => 'storefront_featured_categories_section_category_3_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:3:"207";',
            ],
            86 => [
                'id' => 286,
                'key' => 'storefront_featured_categories_section_category_3_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            87 => [
                'id' => 287,
                'key' => 'storefront_featured_categories_section_category_3_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            88 => [
                'id' => 288,
                'key' => 'storefront_featured_categories_section_category_4_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:2:"82";',
            ],
            89 => [
                'id' => 289,
                'key' => 'storefront_featured_categories_section_category_4_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            90 => [
                'id' => 290,
                'key' => 'storefront_featured_categories_section_category_4_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            91 => [
                'id' => 291,
                'key' => 'storefront_featured_categories_section_category_5_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:2:"12";',
            ],
            92 => [
                'id' => 292,
                'key' => 'storefront_featured_categories_section_category_5_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            93 => [
                'id' => 293,
                'key' => 'storefront_featured_categories_section_category_5_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            94 => [
                'id' => 294,
                'key' => 'storefront_featured_categories_section_category_6_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:3:"120";',
            ],
            95 => [
                'id' => 295,
                'key' => 'storefront_featured_categories_section_category_6_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            96 => [
                'id' => 296,
                'key' => 'storefront_featured_categories_section_category_6_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            97 => [
                'id' => 297,
                'key' => 'storefront_product_tabs_1_section_enabled',
                'is_translatable' => 0,
                'plain_value' => 's:1:"1";',
            ],
            98 => [
                'id' => 298,
                'key' => 'storefront_product_tabs_1_section_tab_1_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            99 => [
                'id' => 299,
                'key' => 'storefront_product_tabs_1_section_tab_1_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:2:"15";',
            ],
            100 => [
                'id' => 300,
                'key' => 'storefront_product_tabs_1_section_tab_1_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            101 => [
                'id' => 301,
                'key' => 'storefront_product_tabs_1_section_tab_2_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            102 => [
                'id' => 302,
                'key' => 'storefront_product_tabs_1_section_tab_2_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:1:"7";',
            ],
            103 => [
                'id' => 303,
                'key' => 'storefront_product_tabs_1_section_tab_2_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            104 => [
                'id' => 304,
                'key' => 'storefront_product_tabs_1_section_tab_3_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            105 => [
                'id' => 305,
                'key' => 'storefront_product_tabs_1_section_tab_3_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:2:"19";',
            ],
            106 => [
                'id' => 306,
                'key' => 'storefront_product_tabs_1_section_tab_3_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            107 => [
                'id' => 307,
                'key' => 'storefront_product_tabs_1_section_tab_4_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            108 => [
                'id' => 308,
                'key' => 'storefront_product_tabs_1_section_tab_4_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:2:"98";',
            ],
            109 => [
                'id' => 309,
                'key' => 'storefront_product_tabs_1_section_tab_4_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            110 => [
                'id' => 310,
                'key' => 'storefront_top_brands_section_enabled',
                'is_translatable' => 0,
                'plain_value' => 's:1:"1";',
            ],
            111 => [
                'id' => 311,
                'key' => 'storefront_flash_sale_and_vertical_products_section_enabled',
                'is_translatable' => 0,
                'plain_value' => 's:1:"1";',
            ],
            112 => [
                'id' => 312,
                'key' => 'storefront_flash_sale_title',
                'is_translatable' => 1,
                'plain_value' => 's:34:"بهترین <b>معاملات</b>";',
                'value' => 's:34:"بهترین <b>معاملات</b>";',
            ],
            113 => [
                'id' => 313,
                'key' => 'storefront_active_flash_sale_campaign',
                'is_translatable' => 0,
                'plain_value' => 's:1:"1";',
            ],
            114 => [
                'id' => 314,
                'key' => 'storefront_vertical_products_1_title',
                'is_translatable' => 1,
                'plain_value' => 's:8:"ساعت";',
                'value' => 's:8:"ساعت";',
            ],
            115 => [
                'id' => 315,
                'key' => 'storefront_vertical_products_1_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            116 => [
                'id' => 316,
                'key' => 'storefront_vertical_products_1_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:2:"82";',
            ],
            117 => [
                'id' => 317,
                'key' => 'storefront_vertical_products_1_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            118 => [
                'id' => 318,
                'key' => 'storefront_vertical_products_2_title',
                'is_translatable' => 1,
                'plain_value' => 's:17:"کوله پشتی";',
                'value' => 's:17:"کوله پشتی";',
            ],
            119 => [
                'id' => 319,
                'key' => 'storefront_vertical_products_2_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            120 => [
                'id' => 320,
                'key' => 'storefront_vertical_products_2_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:2:"98";',
            ],
            121 => [
                'id' => 321,
                'key' => 'storefront_vertical_products_2_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            122 => [
                'id' => 322,
                'key' => 'storefront_vertical_products_3_title',
                'is_translatable' => 1,
                'plain_value' => 's:8:"لباس";',
                'value' => 's:8:"لباس";',
            ],
            123 => [
                'id' => 323,
                'key' => 'storefront_vertical_products_3_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            124 => [
                'id' => 324,
                'key' => 'storefront_vertical_products_3_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:2:"15";',
            ],
            125 => [
                'id' => 325,
                'key' => 'storefront_vertical_products_3_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            126 => [
                'id' => 326,
                'key' => 'storefront_two_column_banners_enabled',
                'is_translatable' => 0,
                'plain_value' => 's:1:"1";',
            ],
            127 => [
                'id' => 327,
                'key' => 'storefront_two_column_banners_1_call_to_action_url',
                'is_translatable' => 0,
                'plain_value' => 's:30:"/categories/ultraslim/products";',
            ],
            128 => [
                'id' => 328,
                'key' => 'storefront_two_column_banners_1_open_in_new_window',
                'is_translatable' => 0,
                'plain_value' => 's:1:"0";',
            ],
            129 => [
                'id' => 329,
                'key' => 'storefront_two_column_banners_2_call_to_action_url',
                'is_translatable' => 0,
                'plain_value' => 's:28:"/categories/watches/products";',
            ],
            130 => [
                'id' => 330,
                'key' => 'storefront_two_column_banners_2_open_in_new_window',
                'is_translatable' => 0,
                'plain_value' => 's:1:"0";',
            ],
            131 => [
                'id' => 331,
                'key' => 'storefront_product_grid_section_enabled',
                'is_translatable' => 0,
                'plain_value' => 's:1:"1";',
            ],
            132 => [
                'id' => 332,
                'key' => 'storefront_product_grid_section_tab_1_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            133 => [
                'id' => 333,
                'key' => 'storefront_product_grid_section_tab_1_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:3:"183";',
            ],
            134 => [
                'id' => 334,
                'key' => 'storefront_product_grid_section_tab_1_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            135 => [
                'id' => 335,
                'key' => 'storefront_product_grid_section_tab_2_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            136 => [
                'id' => 336,
                'key' => 'storefront_product_grid_section_tab_2_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:2:"12";',
            ],
            137 => [
                'id' => 337,
                'key' => 'storefront_product_grid_section_tab_2_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            138 => [
                'id' => 338,
                'key' => 'storefront_product_grid_section_tab_3_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            139 => [
                'id' => 339,
                'key' => 'storefront_product_grid_section_tab_3_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:3:"182";',
            ],
            140 => [
                'id' => 340,
                'key' => 'storefront_product_grid_section_tab_3_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            141 => [
                'id' => 341,
                'key' => 'storefront_product_grid_section_tab_4_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            142 => [
                'id' => 342,
                'key' => 'storefront_product_grid_section_tab_4_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:3:"207";',
            ],
            143 => [
                'id' => 343,
                'key' => 'storefront_product_grid_section_tab_4_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            144 => [
                'id' => 344,
                'key' => 'storefront_three_column_banners_enabled',
                'is_translatable' => 0,
                'plain_value' => 's:1:"1";',
            ],
            145 => [
                'id' => 345,
                'key' => 'storefront_three_column_banners_1_call_to_action_url',
                'is_translatable' => 0,
                'plain_value' => 's:36:"/categories/home-appliances/products";',
            ],
            146 => [
                'id' => 346,
                'key' => 'storefront_three_column_banners_1_open_in_new_window',
                'is_translatable' => 0,
                'plain_value' => 's:1:"0";',
            ],
            147 => [
                'id' => 347,
                'key' => 'storefront_three_column_banners_2_call_to_action_url',
                'is_translatable' => 0,
                'plain_value' => 's:39:"/categories/mobile-accessories/products";',
            ],
            148 => [
                'id' => 348,
                'key' => 'storefront_three_column_banners_2_open_in_new_window',
                'is_translatable' => 0,
                'plain_value' => 's:1:"0";',
            ],
            149 => [
                'id' => 349,
                'key' => 'storefront_three_column_banners_3_call_to_action_url',
                'is_translatable' => 0,
                'plain_value' => 's:28:"/categories/gadgets/products";',
            ],
            150 => [
                'id' => 350,
                'key' => 'storefront_three_column_banners_3_open_in_new_window',
                'is_translatable' => 0,
                'plain_value' => 's:1:"0";',
            ],
            151 => [
                'id' => 351,
                'key' => 'storefront_product_tabs_2_section_enabled',
                'is_translatable' => 0,
                'plain_value' => 's:1:"1";',
            ],
            152 => [
                'id' => 352,
                'key' => 'storefront_product_tabs_2_section_tab_1_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:15:"latest_products";',
            ],
            153 => [
                'id' => 353,
                'key' => 'storefront_product_tabs_2_section_tab_1_category_id',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            154 => [
                'id' => 354,
                'key' => 'storefront_product_tabs_2_section_tab_1_products_limit',
                'is_translatable' => 0,
                'plain_value' => 's:2:"10";',
            ],
            155 => [
                'id' => 355,
                'key' => 'storefront_product_tabs_2_section_tab_2_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:24:"recently_viewed_products";',
            ],
            156 => [
                'id' => 356,
                'key' => 'storefront_product_tabs_2_section_tab_2_category_id',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            157 => [
                'id' => 357,
                'key' => 'storefront_product_tabs_2_section_tab_2_products_limit',
                'is_translatable' => 0,
                'plain_value' => 's:2:"10";',
            ],
            158 => [
                'id' => 358,
                'key' => 'storefront_product_tabs_2_section_tab_3_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            159 => [
                'id' => 359,
                'key' => 'storefront_product_tabs_2_section_tab_3_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:3:"126";',
            ],
            160 => [
                'id' => 360,
                'key' => 'storefront_product_tabs_2_section_tab_3_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            161 => [
                'id' => 361,
                'key' => 'storefront_product_tabs_2_section_tab_4_product_type',
                'is_translatable' => 0,
                'plain_value' => 's:17:"category_products";',
            ],
            162 => [
                'id' => 362,
                'key' => 'storefront_product_tabs_2_section_tab_4_category_id',
                'is_translatable' => 0,
                'plain_value' => 's:2:"35";',
            ],
            163 => [
                'id' => 363,
                'key' => 'storefront_product_tabs_2_section_tab_4_products_limit',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            164 => [
                'id' => 364,
                'key' => 'storefront_one_column_banner_enabled',
                'is_translatable' => 0,
                'plain_value' => 's:1:"1";',
            ],
            165 => [
                'id' => 365,
                'key' => 'storefront_one_column_banner_call_to_action_url',
                'is_translatable' => 0,
                'plain_value' => 's:36:"/categories/home-appliances/products";',
            ],
            166 => [
                'id' => 366,
                'key' => 'storefront_one_column_banner_open_in_new_window',
                'is_translatable' => 0,
                'plain_value' => 's:1:"1";',
            ],
            167 => [
                'id' => 367,
                'key' => 'storefront_footer_tags',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            168 => [
                'id' => 368,
                'key' => 'storefront_featured_categories_section_category_1_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            169 => [
                'id' => 369,
                'key' => 'storefront_featured_categories_section_category_2_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            170 => [
                'id' => 370,
                'key' => 'storefront_featured_categories_section_category_3_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            171 => [
                'id' => 371,
                'key' => 'storefront_featured_categories_section_category_4_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            172 => [
                'id' => 372,
                'key' => 'storefront_featured_categories_section_category_5_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            173 => [
                'id' => 373,
                'key' => 'storefront_featured_categories_section_category_6_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            174 => [
                'id' => 374,
                'key' => 'storefront_product_tabs_1_section_tab_1_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            175 => [
                'id' => 375,
                'key' => 'storefront_product_tabs_1_section_tab_2_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            176 => [
                'id' => 376,
                'key' => 'storefront_product_tabs_1_section_tab_3_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            177 => [
                'id' => 377,
                'key' => 'storefront_product_tabs_1_section_tab_4_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            178 => [
                'id' => 378,
                'key' => 'storefront_top_brands',
                'is_translatable' => 0,
                'plain_value' => 'a:13:{i:0;s:2:"16";i:1;s:2:"14";i:2;s:2:"12";i:3;s:1:"1";i:4;s:1:"5";i:5;s:1:"7";i:6;s:1:"8";i:7;s:2:"15";i:8;s:1:"6";i:9;s:1:"2";i:10;s:2:"18";i:11;s:2:"10";i:12;s:1:"3";}',
            ],
            179 => [
                'id' => 379,
                'key' => 'storefront_vertical_products_1_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            180 => [
                'id' => 380,
                'key' => 'storefront_vertical_products_2_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            181 => [
                'id' => 381,
                'key' => 'storefront_vertical_products_3_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            182 => [
                'id' => 382,
                'key' => 'storefront_product_grid_section_tab_1_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            183 => [
                'id' => 383,
                'key' => 'storefront_product_grid_section_tab_2_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            184 => [
                'id' => 384,
                'key' => 'storefront_product_grid_section_tab_3_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            185 => [
                'id' => 385,
                'key' => 'storefront_product_grid_section_tab_4_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            186 => [
                'id' => 386,
                'key' => 'storefront_product_tabs_2_section_tab_1_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            187 => [
                'id' => 387,
                'key' => 'storefront_product_tabs_2_section_tab_2_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            188 => [
                'id' => 388,
                'key' => 'storefront_product_tabs_2_section_tab_3_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            189 => [
                'id' => 389,
                'key' => 'storefront_product_tabs_2_section_tab_4_products',
                'is_translatable' => 0,
                'plain_value' => 'N;',
            ],
            190 => [
                'id' => 390,
                'key' => 'storefront_header_logo',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:4:"1391";',
            ],
            191 => [
                'id' => 391,
                'key' => 'storefront_mail_logo',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:4:"1391";',
            ],
            192 => [
                'id' => 392,
                'key' => 'storefront_favicon',
                'is_translatable' => 0,
                'plain_value' => 's:4:"1392";',
            ],
            193 => [
                'id' => 393,
                'key' => 'storefront_accepted_payment_methods_image',
                'is_translatable' => 0,
                'plain_value' => 's:4:"1388";',
            ],
            194 => [
                'id' => 394,
                'key' => 'storefront_three_column_full_width_banners_background_file_id',
                'is_translatable' => 0,
                'plain_value' => 's:3:"982";',
            ],
            195 => [
                'id' => 395,
                'key' => 'storefront_newsletter_bg_image',
                'is_translatable' => 0,
                'plain_value' => 's:4:"1395";',
            ],
            196 => [
                'id' => 396,
                'key' => 'storefront_blogs_section_title',
                'is_translatable' => 1,
                'plain_value' => NULL,
                'value' => 's:22:"پست های اخیر";',
            ],
            197 => [
                'id' => 397,
                'key' => 'storefront_display_font',
                'is_translatable' => 0,
                'plain_value' => 's:5:"Inter";',
            ],
            198 => [
                'id' => 398,
                'key' => 'storefront_blogs_section_enabled',
                'is_translatable' => 0,
                'plain_value' => 's:1:"0";',
            ],
            199 => [
                'id' => 399,
                'key' => 'storefront_recent_blogs',
                'is_translatable' => 0,
                'plain_value' => 's:1:"5";',
            ],
            200 => [
                'id' => 427,
                'key' => 'storefront_enamad_script',
                'is_translatable' => 0,
                'plain_value' => 's:114:"<img src="https://niceshop.codenevis.net/storage/media/6AnBrJIx5AjUf2sQwgQ0UuugFD8HpVH3j1fWrlkw.png" alt="enamad">";',
            ],
            201 => [
                'id' => 428,
                'key' => 'storefront_samandehi_script',
                'is_translatable' => 0,
                'plain_value' => 's:114:"<img src="https://niceshop.codenevis.net/storage/media/sLnrN0W8GybCKYjERWD4yJia8A6VdQHj3QSm72Wu.png" alt="enamad">";',
            ],
        ];

        foreach ($settings as $setting) {
            if (!DB::table('settings')->where('key', $setting['key'])->first()) {
                $id = DB::table('settings')->insertGetId([
                    "key"             => $setting['key'],
                    "is_translatable" => $setting['is_translatable'],
                    "plain_value"     => $setting['plain_value'],
                ]);

                if ($setting['is_translatable']) {
                    DB::table('setting_translations')->insert([
                        "setting_id" => $id,
                        "value"      => $setting['value']
                    ]);
                }
            }
        }
    }
}
